export const programs = [
  {
    slug: "strength-conditioning",
    title: "Strength & Conditioning",
    subtitle: "Build raw functional strength from the ground up",
    icon: "🏋️",
    duration: "12 Weeks",
    level: "All Levels",
    price: 12999,
    originalPrice: 18999,
    tag: "Most Popular",
    color: "#C9A84C",
    description: "A comprehensive progressive overload program designed to build real, functional strength. Whether you're a beginner or intermediate, this program adapts to your current level and pushes you further every week.",
    highlights: ["Progressive overload system", "Video exercise library", "Weekly coach check-ins", "Nutrition guidance included", "Private community access", "Certificate on completion"],
    curriculum: [
      { week: "Week 1-3", title: "Foundation Phase", desc: "Master movement patterns, establish baselines and build joint stability." },
      { week: "Week 4-6", title: "Strength Phase", desc: "Progressive loading on compound lifts. Squat, deadlift, press mastery." },
      { week: "Week 7-9", title: "Power Phase", desc: "Introduce explosive movements and functional strength patterns." },
      { week: "Week 10-12", title: "Peak Phase", desc: "Maximal strength testing, deload and transformation assessment." },
    ],
    testimonial: { quote: "I hit a deadlift PR I'd been chasing for 2 years. The programming is next level.", name: "Rahul D.", result: "+40kg on deadlift" },
  },
  {
    slug: "fat-loss-transformation",
    title: "Fat Loss Transformation",
    subtitle: "Science-backed fat loss without crash dieting",
    icon: "🔥",
    duration: "8 Weeks",
    level: "Beginner–Intermediate",
    price: 9999,
    originalPrice: 14999,
    tag: "Best Results",
    color: "#FF6B35",
    description: "Forget crash diets and punishing cardio. This program uses metabolic conditioning, strategic nutrition and lifestyle habits to burn fat sustainably while preserving muscle.",
    highlights: ["Metabolic training system", "Personalised calorie targets", "Weekly body composition tracking", "Recipe bank (100+ recipes)", "Mindset coaching module", "Lifetime access to materials"],
    curriculum: [
      { week: "Week 1-2", title: "Metabolic Reset", desc: "Calibrate your metabolism, eliminate inflammation and set baselines." },
      { week: "Week 3-4", title: "Fat Burn Phase", desc: "High-intensity metabolic training with strategic nutrition timing." },
      { week: "Week 5-6", title: "Accelerate Phase", desc: "Increase training density, refine nutrition and push results harder." },
      { week: "Week 7-8", title: "Sustain & Seal", desc: "Lock in results, build habits and create your long-term plan." },
    ],
    testimonial: { quote: "Lost 12kg in 8 weeks without feeling starved. Shraddha's approach just works.", name: "Priya S.", result: "-12kg in 8 weeks" },
  },
  {
    slug: "nutrition-mastery",
    title: "Nutrition Mastery",
    subtitle: "Understand food science and transform your eating forever",
    icon: "🥗",
    duration: "6 Weeks",
    level: "All Levels",
    price: 7999,
    originalPrice: 11999,
    tag: "Science-Based",
    color: "#4CAF50",
    description: "Stop following fad diets and start understanding the science of nutrition. This program gives you the knowledge and tools to make smart food choices for life — not just for 6 weeks.",
    highlights: ["Macro & micronutrient mastery", "Meal planning templates", "Grocery guides & food labels", "Supplement science module", "Gut health protocol", "Ongoing Q&A access"],
    curriculum: [
      { week: "Week 1", title: "Nutrition Foundations", desc: "Macros, micros, calories — understand what your body actually needs." },
      { week: "Week 2", title: "Food Science", desc: "How food affects hormones, energy, metabolism and performance." },
      { week: "Week 3-4", title: "Meal Planning", desc: "Build your personalised meal plan with templates and portion guides." },
      { week: "Week 5-6", title: "Lifestyle Integration", desc: "Eating out, social events, travel — make nutrition sustainable forever." },
    ],
    testimonial: { quote: "For the first time I understand WHY I'm eating what I'm eating. Life changing.", name: "Anjali M.", result: "Lost 8kg, gained energy" },
  },
  {
    slug: "wellness-mindset",
    title: "Wellness & Mindset",
    subtitle: "Holistic health — body, mind and spirit",
    icon: "🧘",
    duration: "4 Weeks",
    level: "All Levels",
    price: 5999,
    originalPrice: 8999,
    tag: "Holistic",
    color: "#9C27B0",
    description: "The missing piece in most fitness journeys. Sleep, stress, recovery and mental performance are the foundations that make everything else work. This module transforms how you approach your whole life.",
    highlights: ["Sleep optimisation protocol", "Stress & cortisol management", "Breathwork & recovery tools", "Mindset & habit science", "Daily wellness routines", "Mental performance coaching"],
    curriculum: [
      { week: "Week 1", title: "Sleep Science", desc: "Optimise your sleep for recovery, fat loss and performance." },
      { week: "Week 2", title: "Stress & Recovery", desc: "Manage cortisol, reduce inflammation and recover faster." },
      { week: "Week 3", title: "Mindset Mastery", desc: "Build discipline, overcome limiting beliefs and stay consistent." },
      { week: "Week 4", title: "Integrated Wellness", desc: "Combine all pillars into a daily routine that sticks." },
    ],
    testimonial: { quote: "My sleep improved in week 1. My whole life has changed since doing this module.", name: "Vikram R.", result: "Better sleep, less stress" },
  },
  {
    slug: "elite-1on1-coaching",
    title: "Elite 1-on-1 Coaching",
    subtitle: "Direct coaching with Shraddha Gadit",
    icon: "👑",
    duration: "3 Months",
    level: "All Levels",
    price: 29999,
    originalPrice: 45000,
    tag: "Premium",
    color: "#C9A84C",
    description: "The most personalised coaching experience at KPF Academy. Work directly with Shraddha Gadit on a fully customised program built around your unique goals, body type, lifestyle and schedule.",
    highlights: ["Fully custom program design", "Weekly 1-on-1 video calls", "Daily WhatsApp support", "Nutrition plan & adjustments", "Priority response guarantee", "Unlimited program revisions"],
    curriculum: [
      { week: "Month 1", title: "Assessment & Foundation", desc: "Deep dive assessment, baseline testing and custom program design." },
      { week: "Month 2", title: "Execution & Optimisation", desc: "Full program execution with weekly adjustments based on progress." },
      { week: "Month 3", title: "Peak & Sustain", desc: "Peak performance phase and building your long-term independent plan." },
    ],
    testimonial: { quote: "Worth every rupee. Shraddha's attention to detail is unmatched.", name: "Neha T.", result: "Complete transformation" },
  },
  {
    slug: "fitness-education-course",
    title: "Fitness Education Course",
    subtitle: "Become a certified fitness professional",
    icon: "🎓",
    duration: "Self-Paced",
    level: "Beginner–Advanced",
    price: 15999,
    originalPrice: 22999,
    tag: "Career Track",
    color: "#2196F3",
    description: "Learn the science of fitness and nutrition at a professional level. Ideal for aspiring coaches, fitness enthusiasts or anyone who wants to train themselves and others with confidence and credibility.",
    highlights: ["Exercise science fundamentals", "Anatomy & physiology", "Program design principles", "Client assessment tools", "Business of fitness module", "KPF Academy Certificate"],
    curriculum: [
      { week: "Module 1", title: "Exercise Science", desc: "Anatomy, physiology and biomechanics for fitness professionals." },
      { week: "Module 2", title: "Nutrition Science", desc: "Sports nutrition, meal planning and dietary assessment." },
      { week: "Module 3", title: "Program Design", desc: "Design effective programs for different goals and populations." },
      { week: "Module 4", title: "Professional Practice", desc: "Client management, assessment and building your fitness career." },
    ],
    testimonial: { quote: "This course gave me the knowledge and confidence to start my own coaching practice.", name: "Rohan K.", result: "Now a certified coach" },
  },
];

export const workshops = [
  {
    slug: "nutrition-masterclass",
    title: "Nutrition Masterclass",
    date: "Every Saturday",
    duration: "3 Hours",
    price: 1999,
    mode: "Online & In-Person",
    desc: "A deep-dive into evidence-based nutrition with Shraddha Gadit. Learn what actually works, what doesn't and why.",
    spots: 20,
  },
  {
    slug: "fat-loss-workshop",
    title: "Fat Loss Blueprint Workshop",
    date: "2nd Sunday of Month",
    duration: "4 Hours",
    price: 2499,
    mode: "Online",
    desc: "The complete fat loss system in one intensive workshop. Leave with a personalised plan ready to execute.",
    spots: 30,
  },
  {
    slug: "mindset-performance",
    title: "Mindset & Performance",
    date: "Last Friday of Month",
    duration: "2 Hours",
    price: 1499,
    mode: "Online",
    desc: "Mental performance, habit science and the psychology of lasting change. A workshop that transforms your mindset.",
    spots: 50,
  },
];

export const blogPosts = [
  {
    slug: "science-of-fat-loss",
    title: "The Real Science of Fat Loss (That No One Talks About)",
    category: "Nutrition",
    date: "March 10, 2026",
    readTime: "8 min read",
    excerpt: "Forget everything fad diets told you. Here's what the science actually says about losing fat sustainably and keeping it off forever.",
    content: "Fat loss is one of the most misunderstood topics in the fitness industry. The internet is flooded with conflicting advice — keto, intermittent fasting, calorie counting, cleanses. But what does the science actually say?\n\nAt its core, fat loss comes down to one principle: a sustained caloric deficit. When your body consistently burns more energy than it consumes, it turns to stored fat as fuel. This is not negotiable — it is basic thermodynamics.\n\nHowever, the quality of your deficit matters enormously. A deficit created by crash dieting leads to muscle loss, metabolic adaptation and rebound weight gain. A deficit created through strategic nutrition and progressive training preserves muscle, keeps your metabolism elevated and produces lasting results.\n\nThe three pillars of sustainable fat loss are: adequate protein intake (at least 1.6g per kg of bodyweight), progressive resistance training to preserve muscle mass, and a moderate caloric deficit of 300-500 calories per day.\n\nShraddha Gadit and the KPF Academy approach every fat loss program with this evidence-based foundation — which is why our clients get results that last.",
  },
  {
    slug: "protein-myths-busted",
    title: "5 Protein Myths That Are Sabotaging Your Results",
    category: "Nutrition",
    date: "March 3, 2026",
    readTime: "6 min read",
    excerpt: "Too much protein damages your kidneys? You can only absorb 30g at a time? Let's bust the most common protein myths with actual science.",
    content: "Protein is arguably the most important macronutrient for body composition, yet it's also the most misunderstood. Here are five myths we hear constantly at KPF Academy — and what the science actually says.\n\nMyth 1: High protein damages your kidneys. This myth is only relevant for people with pre-existing kidney disease. For healthy individuals, high protein diets have shown no negative effects on kidney function in multiple large studies.\n\nMyth 2: You can only absorb 30g of protein per meal. Your body can absolutely absorb more than 30g of protein in a single meal — it just does so more slowly. Total daily protein intake matters far more than per-meal amounts.\n\nMyth 3: Plant protein is inferior to animal protein. While animal proteins tend to have better amino acid profiles, you can absolutely meet all your protein needs through plant sources with thoughtful food combining.\n\nMyth 4: You need protein immediately after training. The post-workout anabolic window is much wider than the fitness industry suggests — typically 4-6 hours. Total daily protein intake is what drives results.\n\nMyth 5: More protein always means more muscle. Beyond approximately 2.2g per kg of bodyweight, additional protein shows diminishing returns. Progressive training stimulus is the primary driver of muscle growth.",
  },
  {
    slug: "sleep-and-fitness",
    title: "Why Sleep Is Your Most Powerful Fitness Tool",
    category: "Wellness",
    date: "February 24, 2026",
    readTime: "7 min read",
    excerpt: "You can have the perfect training program and diet, but if your sleep is poor, you're leaving 50% of your results on the table.",
    content: "In 17 years of coaching, the single most underrated factor in fitness results is sleep. We obsess over training programs and nutrition plans, but consistently overlook the 7-9 hours that determine whether all that hard work actually pays off.\n\nDuring deep sleep, your body releases growth hormone — the primary driver of muscle repair and fat metabolism. Poor sleep suppresses growth hormone secretion by up to 70%, meaning your muscles recover slower and your fat-burning capacity is significantly diminished.\n\nSleep deprivation also dramatically affects hunger hormones. Ghrelin (the hunger hormone) increases by 28% with poor sleep, while leptin (the satiety hormone) decreases by 18%. This is why you feel hungrier and crave higher-calorie foods when you're sleep deprived.\n\nFor optimal fitness results, prioritise: consistent sleep and wake times (even on weekends), a cool, dark bedroom environment (18-20°C is optimal), no screens 60 minutes before bed, and no caffeine after 2pm.\n\nAt KPF Academy, sleep optimisation is a core part of every coaching program — because without it, you're building on sand.",
  },
  {
    slug: "strength-training-women",
    title: "Why Every Woman Should Strength Train",
    category: "Training",
    date: "February 17, 2026",
    readTime: "5 min read",
    excerpt: "Strength training won't make you bulky — it will make you strong, confident and metabolically powerful. Here's the science.",
    content: "One of the most persistent and damaging myths in women's fitness is that strength training will make you look bulky or masculine. This myth has kept millions of women away from the training modality that would benefit them most.\n\nThe reality: women have approximately 15-20 times less testosterone than men. This hormonal difference makes it physiologically very difficult for women to build the kind of muscle mass associated with a bulky appearance. What strength training actually does for women is build lean, defined muscle, dramatically increase metabolic rate, improve bone density (crucial for preventing osteoporosis), enhance posture, and build functional strength for everyday life.\n\nResearch consistently shows that women who strength train have better body composition outcomes than those who do cardio alone — they lose more fat, maintain more muscle and have higher resting metabolic rates.\n\nAt KPF Academy, all of our programs — for men and women — are built on a foundation of progressive resistance training, because the science is unambiguous: it is the most effective tool for body composition, health and longevity.",
  },
];

export const testimonials = [
  { name: "Priya Sharma", location: "Mumbai", program: "Fat Loss Transformation", result: "Lost 14kg", period: "8 weeks", quote: "I had tried everything — keto, intermittent fasting, crash diets. Nothing worked long term. KPF Academy's approach is completely different. Shraddha taught me the science, not just the rules. I lost 14kg and I've kept it off for 6 months.", rating: 5 },
  { name: "Rahul Desai", location: "Pune", program: "Strength & Conditioning", result: "+45kg on deadlift", period: "12 weeks", quote: "The programming is unlike anything I've followed before. Every week made sense. I hit lifts I'd been chasing for years and came out understanding training in a completely different way.", rating: 5 },
  { name: "Anjali Mehta", location: "Bangalore", program: "Nutrition Mastery", result: "Transformed relationship with food", period: "6 weeks", quote: "This course changed how I think about food entirely. No more guilt, no more confusion. Just clear science-backed principles that I can follow for life.", rating: 5 },
  { name: "Vikram Rao", location: "Delhi", program: "Elite 1-on-1 Coaching", result: "Complete body transformation", period: "3 months", quote: "Working directly with Shraddha is an experience unlike any other. The attention to detail, the adjustments week by week, the support — it's worth every rupee.", rating: 5 },
  { name: "Neha Kapoor", location: "Mumbai", program: "Wellness & Mindset", result: "Better sleep, zero stress", period: "4 weeks", quote: "I came in thinking mindset stuff wasn't for me. I leave having completely transformed how I sleep, manage stress and approach my health. Genuinely life-changing.", rating: 5 },
  { name: "Arjun Nair", location: "Chennai", program: "Fitness Education Course", result: "Became a certified coach", period: "Self-paced", quote: "The knowledge in this course is incredible. I've read textbooks that don't cover what Shraddha covers in this program. I now run my own coaching practice.", rating: 5 },
];

export const pricingPlans = [
  {
    name: "STARTER",
    price: 4999,
    period: "one-time",
    desc: "Perfect for beginners ready to start their fitness journey with proven fundamentals.",
    features: ["Access to 1 program of choice", "Video exercise library", "Nutrition basics guide", "Community access", "Email support", "Certificate on completion"],
    cta: "Get Started",
    highlight: false,
  },
  {
    name: "TRANSFORM",
    price: 14999,
    period: "3 months",
    desc: "The complete transformation package — training, nutrition and wellness all in one.",
    features: ["Access to ALL programs", "Personalised nutrition plan", "Weekly group coaching calls", "WhatsApp community", "Priority email support", "Progress tracking tools", "All future program updates", "KPF Academy Certificate"],
    cta: "Start Transforming",
    highlight: true,
    tag: "Most Popular",
  },
  {
    name: "ELITE",
    price: 29999,
    period: "3 months",
    desc: "Maximum results with direct 1-on-1 access to Shraddha Gadit.",
    features: ["Everything in Transform", "Weekly 1-on-1 video call with Shraddha", "Custom program design", "Daily WhatsApp support", "Nutrition plan adjustments", "Unlimited program revisions", "Priority response (within 2hrs)", "Lifetime community access"],
    cta: "Apply for Elite",
    highlight: false,
  },
];
